repos:
-   repo: local
    hooks:
    -   id: zetasql_formatter
        name: ZetaSQL Formatter
        files: \.(bq|sql)$
        language: docker_image
        entry: matts966/zetasql-formatter:latest
