# Ignore everything
**

# Allow files and directories
!bazel/*
!alphasql/*
!.bazelrc
!.bazelversion
!WORKSPACE

# Ignore unnecessary files inside allowed directories
# This should go after the allowed directories
**/.DS_Store
