// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: type.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_type_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_type_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/descriptor.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_type_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_type_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[6]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_type_2eproto;
namespace zetasql {
class ArrayTypeProto;
struct ArrayTypeProtoDefaultTypeInternal;
extern ArrayTypeProtoDefaultTypeInternal _ArrayTypeProto_default_instance_;
class EnumTypeProto;
struct EnumTypeProtoDefaultTypeInternal;
extern EnumTypeProtoDefaultTypeInternal _EnumTypeProto_default_instance_;
class ProtoTypeProto;
struct ProtoTypeProtoDefaultTypeInternal;
extern ProtoTypeProtoDefaultTypeInternal _ProtoTypeProto_default_instance_;
class StructFieldProto;
struct StructFieldProtoDefaultTypeInternal;
extern StructFieldProtoDefaultTypeInternal _StructFieldProto_default_instance_;
class StructTypeProto;
struct StructTypeProtoDefaultTypeInternal;
extern StructTypeProtoDefaultTypeInternal _StructTypeProto_default_instance_;
class TypeProto;
struct TypeProtoDefaultTypeInternal;
extern TypeProtoDefaultTypeInternal _TypeProto_default_instance_;
}  // namespace zetasql
PROTOBUF_NAMESPACE_OPEN
template<> ::zetasql::ArrayTypeProto* Arena::CreateMaybeMessage<::zetasql::ArrayTypeProto>(Arena*);
template<> ::zetasql::EnumTypeProto* Arena::CreateMaybeMessage<::zetasql::EnumTypeProto>(Arena*);
template<> ::zetasql::ProtoTypeProto* Arena::CreateMaybeMessage<::zetasql::ProtoTypeProto>(Arena*);
template<> ::zetasql::StructFieldProto* Arena::CreateMaybeMessage<::zetasql::StructFieldProto>(Arena*);
template<> ::zetasql::StructTypeProto* Arena::CreateMaybeMessage<::zetasql::StructTypeProto>(Arena*);
template<> ::zetasql::TypeProto* Arena::CreateMaybeMessage<::zetasql::TypeProto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace zetasql {

enum TypeKind : int {
  __TypeKind__switch_must_have_a_default__ = -1,
  TYPE_UNKNOWN = 0,
  TYPE_INT32 = 1,
  TYPE_INT64 = 2,
  TYPE_UINT32 = 3,
  TYPE_UINT64 = 4,
  TYPE_BOOL = 5,
  TYPE_FLOAT = 6,
  TYPE_DOUBLE = 7,
  TYPE_STRING = 8,
  TYPE_BYTES = 9,
  TYPE_DATE = 10,
  TYPE_TIMESTAMP = 19,
  TYPE_ENUM = 15,
  TYPE_ARRAY = 16,
  TYPE_STRUCT = 17,
  TYPE_PROTO = 18,
  TYPE_TIME = 20,
  TYPE_DATETIME = 21,
  TYPE_GEOGRAPHY = 22,
  TYPE_NUMERIC = 23,
  TYPE_BIGNUMERIC = 24,
  TYPE_EXTENDED = 25,
  TYPE_JSON = 26,
  TYPE_INTERVAL = 27,
  TYPE_TOKENLIST = 28
};
bool TypeKind_IsValid(int value);
constexpr TypeKind TypeKind_MIN = __TypeKind__switch_must_have_a_default__;
constexpr TypeKind TypeKind_MAX = TYPE_TOKENLIST;
constexpr int TypeKind_ARRAYSIZE = TypeKind_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TypeKind_descriptor();
template<typename T>
inline const std::string& TypeKind_Name(T enum_t_value) {
  static_assert(::std::is_same<T, TypeKind>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function TypeKind_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    TypeKind_descriptor(), enum_t_value);
}
inline bool TypeKind_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, TypeKind* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<TypeKind>(
    TypeKind_descriptor(), name, value);
}
// ===================================================================

class TypeProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:zetasql.TypeProto) */ {
 public:
  inline TypeProto() : TypeProto(nullptr) {}
  ~TypeProto() override;
  explicit constexpr TypeProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TypeProto(const TypeProto& from);
  TypeProto(TypeProto&& from) noexcept
    : TypeProto() {
    *this = ::std::move(from);
  }

  inline TypeProto& operator=(const TypeProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline TypeProto& operator=(TypeProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TypeProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const TypeProto* internal_default_instance() {
    return reinterpret_cast<const TypeProto*>(
               &_TypeProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TypeProto& a, TypeProto& b) {
    a.Swap(&b);
  }
  inline void Swap(TypeProto* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TypeProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TypeProto* New() const final {
    return new TypeProto();
  }

  TypeProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TypeProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TypeProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const TypeProto& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TypeProto* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "zetasql.TypeProto";
  }
  protected:
  explicit TypeProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFileDescriptorSetFieldNumber = 6,
    kArrayTypeFieldNumber = 2,
    kStructTypeFieldNumber = 3,
    kProtoTypeFieldNumber = 4,
    kEnumTypeFieldNumber = 5,
    kTypeKindFieldNumber = 1,
  };
  // repeated .google.protobuf.FileDescriptorSet file_descriptor_set = 6;
  int file_descriptor_set_size() const;
  private:
  int _internal_file_descriptor_set_size() const;
  public:
  void clear_file_descriptor_set();
  PROTOBUF_NAMESPACE_ID::FileDescriptorSet* mutable_file_descriptor_set(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< PROTOBUF_NAMESPACE_ID::FileDescriptorSet >*
      mutable_file_descriptor_set();
  private:
  const PROTOBUF_NAMESPACE_ID::FileDescriptorSet& _internal_file_descriptor_set(int index) const;
  PROTOBUF_NAMESPACE_ID::FileDescriptorSet* _internal_add_file_descriptor_set();
  public:
  const PROTOBUF_NAMESPACE_ID::FileDescriptorSet& file_descriptor_set(int index) const;
  PROTOBUF_NAMESPACE_ID::FileDescriptorSet* add_file_descriptor_set();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< PROTOBUF_NAMESPACE_ID::FileDescriptorSet >&
      file_descriptor_set() const;

  // optional .zetasql.ArrayTypeProto array_type = 2;
  bool has_array_type() const;
  private:
  bool _internal_has_array_type() const;
  public:
  void clear_array_type();
  const ::zetasql::ArrayTypeProto& array_type() const;
  PROTOBUF_MUST_USE_RESULT ::zetasql::ArrayTypeProto* release_array_type();
  ::zetasql::ArrayTypeProto* mutable_array_type();
  void set_allocated_array_type(::zetasql::ArrayTypeProto* array_type);
  private:
  const ::zetasql::ArrayTypeProto& _internal_array_type() const;
  ::zetasql::ArrayTypeProto* _internal_mutable_array_type();
  public:
  void unsafe_arena_set_allocated_array_type(
      ::zetasql::ArrayTypeProto* array_type);
  ::zetasql::ArrayTypeProto* unsafe_arena_release_array_type();

  // optional .zetasql.StructTypeProto struct_type = 3;
  bool has_struct_type() const;
  private:
  bool _internal_has_struct_type() const;
  public:
  void clear_struct_type();
  const ::zetasql::StructTypeProto& struct_type() const;
  PROTOBUF_MUST_USE_RESULT ::zetasql::StructTypeProto* release_struct_type();
  ::zetasql::StructTypeProto* mutable_struct_type();
  void set_allocated_struct_type(::zetasql::StructTypeProto* struct_type);
  private:
  const ::zetasql::StructTypeProto& _internal_struct_type() const;
  ::zetasql::StructTypeProto* _internal_mutable_struct_type();
  public:
  void unsafe_arena_set_allocated_struct_type(
      ::zetasql::StructTypeProto* struct_type);
  ::zetasql::StructTypeProto* unsafe_arena_release_struct_type();

  // optional .zetasql.ProtoTypeProto proto_type = 4;
  bool has_proto_type() const;
  private:
  bool _internal_has_proto_type() const;
  public:
  void clear_proto_type();
  const ::zetasql::ProtoTypeProto& proto_type() const;
  PROTOBUF_MUST_USE_RESULT ::zetasql::ProtoTypeProto* release_proto_type();
  ::zetasql::ProtoTypeProto* mutable_proto_type();
  void set_allocated_proto_type(::zetasql::ProtoTypeProto* proto_type);
  private:
  const ::zetasql::ProtoTypeProto& _internal_proto_type() const;
  ::zetasql::ProtoTypeProto* _internal_mutable_proto_type();
  public:
  void unsafe_arena_set_allocated_proto_type(
      ::zetasql::ProtoTypeProto* proto_type);
  ::zetasql::ProtoTypeProto* unsafe_arena_release_proto_type();

  // optional .zetasql.EnumTypeProto enum_type = 5;
  bool has_enum_type() const;
  private:
  bool _internal_has_enum_type() const;
  public:
  void clear_enum_type();
  const ::zetasql::EnumTypeProto& enum_type() const;
  PROTOBUF_MUST_USE_RESULT ::zetasql::EnumTypeProto* release_enum_type();
  ::zetasql::EnumTypeProto* mutable_enum_type();
  void set_allocated_enum_type(::zetasql::EnumTypeProto* enum_type);
  private:
  const ::zetasql::EnumTypeProto& _internal_enum_type() const;
  ::zetasql::EnumTypeProto* _internal_mutable_enum_type();
  public:
  void unsafe_arena_set_allocated_enum_type(
      ::zetasql::EnumTypeProto* enum_type);
  ::zetasql::EnumTypeProto* unsafe_arena_release_enum_type();

  // optional .zetasql.TypeKind type_kind = 1;
  bool has_type_kind() const;
  private:
  bool _internal_has_type_kind() const;
  public:
  void clear_type_kind();
  ::zetasql::TypeKind type_kind() const;
  void set_type_kind(::zetasql::TypeKind value);
  private:
  ::zetasql::TypeKind _internal_type_kind() const;
  void _internal_set_type_kind(::zetasql::TypeKind value);
  public:

  // @@protoc_insertion_point(class_scope:zetasql.TypeProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< PROTOBUF_NAMESPACE_ID::FileDescriptorSet > file_descriptor_set_;
  ::zetasql::ArrayTypeProto* array_type_;
  ::zetasql::StructTypeProto* struct_type_;
  ::zetasql::ProtoTypeProto* proto_type_;
  ::zetasql::EnumTypeProto* enum_type_;
  int type_kind_;
  friend struct ::TableStruct_type_2eproto;
};
// -------------------------------------------------------------------

class ArrayTypeProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:zetasql.ArrayTypeProto) */ {
 public:
  inline ArrayTypeProto() : ArrayTypeProto(nullptr) {}
  ~ArrayTypeProto() override;
  explicit constexpr ArrayTypeProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ArrayTypeProto(const ArrayTypeProto& from);
  ArrayTypeProto(ArrayTypeProto&& from) noexcept
    : ArrayTypeProto() {
    *this = ::std::move(from);
  }

  inline ArrayTypeProto& operator=(const ArrayTypeProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline ArrayTypeProto& operator=(ArrayTypeProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ArrayTypeProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const ArrayTypeProto* internal_default_instance() {
    return reinterpret_cast<const ArrayTypeProto*>(
               &_ArrayTypeProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ArrayTypeProto& a, ArrayTypeProto& b) {
    a.Swap(&b);
  }
  inline void Swap(ArrayTypeProto* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ArrayTypeProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ArrayTypeProto* New() const final {
    return new ArrayTypeProto();
  }

  ArrayTypeProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ArrayTypeProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ArrayTypeProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ArrayTypeProto& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ArrayTypeProto* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "zetasql.ArrayTypeProto";
  }
  protected:
  explicit ArrayTypeProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kElementTypeFieldNumber = 1,
  };
  // optional .zetasql.TypeProto element_type = 1;
  bool has_element_type() const;
  private:
  bool _internal_has_element_type() const;
  public:
  void clear_element_type();
  const ::zetasql::TypeProto& element_type() const;
  PROTOBUF_MUST_USE_RESULT ::zetasql::TypeProto* release_element_type();
  ::zetasql::TypeProto* mutable_element_type();
  void set_allocated_element_type(::zetasql::TypeProto* element_type);
  private:
  const ::zetasql::TypeProto& _internal_element_type() const;
  ::zetasql::TypeProto* _internal_mutable_element_type();
  public:
  void unsafe_arena_set_allocated_element_type(
      ::zetasql::TypeProto* element_type);
  ::zetasql::TypeProto* unsafe_arena_release_element_type();

  // @@protoc_insertion_point(class_scope:zetasql.ArrayTypeProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::zetasql::TypeProto* element_type_;
  friend struct ::TableStruct_type_2eproto;
};
// -------------------------------------------------------------------

class StructFieldProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:zetasql.StructFieldProto) */ {
 public:
  inline StructFieldProto() : StructFieldProto(nullptr) {}
  ~StructFieldProto() override;
  explicit constexpr StructFieldProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StructFieldProto(const StructFieldProto& from);
  StructFieldProto(StructFieldProto&& from) noexcept
    : StructFieldProto() {
    *this = ::std::move(from);
  }

  inline StructFieldProto& operator=(const StructFieldProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline StructFieldProto& operator=(StructFieldProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StructFieldProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const StructFieldProto* internal_default_instance() {
    return reinterpret_cast<const StructFieldProto*>(
               &_StructFieldProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(StructFieldProto& a, StructFieldProto& b) {
    a.Swap(&b);
  }
  inline void Swap(StructFieldProto* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StructFieldProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline StructFieldProto* New() const final {
    return new StructFieldProto();
  }

  StructFieldProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<StructFieldProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const StructFieldProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const StructFieldProto& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StructFieldProto* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "zetasql.StructFieldProto";
  }
  protected:
  explicit StructFieldProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFieldNameFieldNumber = 1,
    kFieldTypeFieldNumber = 2,
  };
  // optional string field_name = 1;
  bool has_field_name() const;
  private:
  bool _internal_has_field_name() const;
  public:
  void clear_field_name();
  const std::string& field_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_field_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_field_name();
  PROTOBUF_MUST_USE_RESULT std::string* release_field_name();
  void set_allocated_field_name(std::string* field_name);
  private:
  const std::string& _internal_field_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_field_name(const std::string& value);
  std::string* _internal_mutable_field_name();
  public:

  // optional .zetasql.TypeProto field_type = 2;
  bool has_field_type() const;
  private:
  bool _internal_has_field_type() const;
  public:
  void clear_field_type();
  const ::zetasql::TypeProto& field_type() const;
  PROTOBUF_MUST_USE_RESULT ::zetasql::TypeProto* release_field_type();
  ::zetasql::TypeProto* mutable_field_type();
  void set_allocated_field_type(::zetasql::TypeProto* field_type);
  private:
  const ::zetasql::TypeProto& _internal_field_type() const;
  ::zetasql::TypeProto* _internal_mutable_field_type();
  public:
  void unsafe_arena_set_allocated_field_type(
      ::zetasql::TypeProto* field_type);
  ::zetasql::TypeProto* unsafe_arena_release_field_type();

  // @@protoc_insertion_point(class_scope:zetasql.StructFieldProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr field_name_;
  ::zetasql::TypeProto* field_type_;
  friend struct ::TableStruct_type_2eproto;
};
// -------------------------------------------------------------------

class StructTypeProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:zetasql.StructTypeProto) */ {
 public:
  inline StructTypeProto() : StructTypeProto(nullptr) {}
  ~StructTypeProto() override;
  explicit constexpr StructTypeProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StructTypeProto(const StructTypeProto& from);
  StructTypeProto(StructTypeProto&& from) noexcept
    : StructTypeProto() {
    *this = ::std::move(from);
  }

  inline StructTypeProto& operator=(const StructTypeProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline StructTypeProto& operator=(StructTypeProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StructTypeProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const StructTypeProto* internal_default_instance() {
    return reinterpret_cast<const StructTypeProto*>(
               &_StructTypeProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(StructTypeProto& a, StructTypeProto& b) {
    a.Swap(&b);
  }
  inline void Swap(StructTypeProto* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StructTypeProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline StructTypeProto* New() const final {
    return new StructTypeProto();
  }

  StructTypeProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<StructTypeProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const StructTypeProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const StructTypeProto& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StructTypeProto* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "zetasql.StructTypeProto";
  }
  protected:
  explicit StructTypeProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFieldFieldNumber = 1,
  };
  // repeated .zetasql.StructFieldProto field = 1;
  int field_size() const;
  private:
  int _internal_field_size() const;
  public:
  void clear_field();
  ::zetasql::StructFieldProto* mutable_field(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::zetasql::StructFieldProto >*
      mutable_field();
  private:
  const ::zetasql::StructFieldProto& _internal_field(int index) const;
  ::zetasql::StructFieldProto* _internal_add_field();
  public:
  const ::zetasql::StructFieldProto& field(int index) const;
  ::zetasql::StructFieldProto* add_field();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::zetasql::StructFieldProto >&
      field() const;

  // @@protoc_insertion_point(class_scope:zetasql.StructTypeProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::zetasql::StructFieldProto > field_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_type_2eproto;
};
// -------------------------------------------------------------------

class ProtoTypeProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:zetasql.ProtoTypeProto) */ {
 public:
  inline ProtoTypeProto() : ProtoTypeProto(nullptr) {}
  ~ProtoTypeProto() override;
  explicit constexpr ProtoTypeProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ProtoTypeProto(const ProtoTypeProto& from);
  ProtoTypeProto(ProtoTypeProto&& from) noexcept
    : ProtoTypeProto() {
    *this = ::std::move(from);
  }

  inline ProtoTypeProto& operator=(const ProtoTypeProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProtoTypeProto& operator=(ProtoTypeProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProtoTypeProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const ProtoTypeProto* internal_default_instance() {
    return reinterpret_cast<const ProtoTypeProto*>(
               &_ProtoTypeProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(ProtoTypeProto& a, ProtoTypeProto& b) {
    a.Swap(&b);
  }
  inline void Swap(ProtoTypeProto* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProtoTypeProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ProtoTypeProto* New() const final {
    return new ProtoTypeProto();
  }

  ProtoTypeProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ProtoTypeProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ProtoTypeProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ProtoTypeProto& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProtoTypeProto* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "zetasql.ProtoTypeProto";
  }
  protected:
  explicit ProtoTypeProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCatalogNamePathFieldNumber = 4,
    kProtoNameFieldNumber = 1,
    kProtoFileNameFieldNumber = 2,
    kFileDescriptorSetIndexFieldNumber = 3,
  };
  // repeated string catalog_name_path = 4;
  int catalog_name_path_size() const;
  private:
  int _internal_catalog_name_path_size() const;
  public:
  void clear_catalog_name_path();
  const std::string& catalog_name_path(int index) const;
  std::string* mutable_catalog_name_path(int index);
  void set_catalog_name_path(int index, const std::string& value);
  void set_catalog_name_path(int index, std::string&& value);
  void set_catalog_name_path(int index, const char* value);
  void set_catalog_name_path(int index, const char* value, size_t size);
  std::string* add_catalog_name_path();
  void add_catalog_name_path(const std::string& value);
  void add_catalog_name_path(std::string&& value);
  void add_catalog_name_path(const char* value);
  void add_catalog_name_path(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& catalog_name_path() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_catalog_name_path();
  private:
  const std::string& _internal_catalog_name_path(int index) const;
  std::string* _internal_add_catalog_name_path();
  public:

  // optional string proto_name = 1;
  bool has_proto_name() const;
  private:
  bool _internal_has_proto_name() const;
  public:
  void clear_proto_name();
  const std::string& proto_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_proto_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_proto_name();
  PROTOBUF_MUST_USE_RESULT std::string* release_proto_name();
  void set_allocated_proto_name(std::string* proto_name);
  private:
  const std::string& _internal_proto_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_proto_name(const std::string& value);
  std::string* _internal_mutable_proto_name();
  public:

  // optional string proto_file_name = 2;
  bool has_proto_file_name() const;
  private:
  bool _internal_has_proto_file_name() const;
  public:
  void clear_proto_file_name();
  const std::string& proto_file_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_proto_file_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_proto_file_name();
  PROTOBUF_MUST_USE_RESULT std::string* release_proto_file_name();
  void set_allocated_proto_file_name(std::string* proto_file_name);
  private:
  const std::string& _internal_proto_file_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_proto_file_name(const std::string& value);
  std::string* _internal_mutable_proto_file_name();
  public:

  // optional int32 file_descriptor_set_index = 3 [default = 0];
  bool has_file_descriptor_set_index() const;
  private:
  bool _internal_has_file_descriptor_set_index() const;
  public:
  void clear_file_descriptor_set_index();
  ::PROTOBUF_NAMESPACE_ID::int32 file_descriptor_set_index() const;
  void set_file_descriptor_set_index(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_file_descriptor_set_index() const;
  void _internal_set_file_descriptor_set_index(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:zetasql.ProtoTypeProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> catalog_name_path_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr proto_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr proto_file_name_;
  ::PROTOBUF_NAMESPACE_ID::int32 file_descriptor_set_index_;
  friend struct ::TableStruct_type_2eproto;
};
// -------------------------------------------------------------------

class EnumTypeProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:zetasql.EnumTypeProto) */ {
 public:
  inline EnumTypeProto() : EnumTypeProto(nullptr) {}
  ~EnumTypeProto() override;
  explicit constexpr EnumTypeProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  EnumTypeProto(const EnumTypeProto& from);
  EnumTypeProto(EnumTypeProto&& from) noexcept
    : EnumTypeProto() {
    *this = ::std::move(from);
  }

  inline EnumTypeProto& operator=(const EnumTypeProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline EnumTypeProto& operator=(EnumTypeProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EnumTypeProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const EnumTypeProto* internal_default_instance() {
    return reinterpret_cast<const EnumTypeProto*>(
               &_EnumTypeProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(EnumTypeProto& a, EnumTypeProto& b) {
    a.Swap(&b);
  }
  inline void Swap(EnumTypeProto* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EnumTypeProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline EnumTypeProto* New() const final {
    return new EnumTypeProto();
  }

  EnumTypeProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<EnumTypeProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const EnumTypeProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const EnumTypeProto& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EnumTypeProto* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "zetasql.EnumTypeProto";
  }
  protected:
  explicit EnumTypeProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCatalogNamePathFieldNumber = 4,
    kEnumNameFieldNumber = 1,
    kEnumFileNameFieldNumber = 2,
    kFileDescriptorSetIndexFieldNumber = 3,
  };
  // repeated string catalog_name_path = 4;
  int catalog_name_path_size() const;
  private:
  int _internal_catalog_name_path_size() const;
  public:
  void clear_catalog_name_path();
  const std::string& catalog_name_path(int index) const;
  std::string* mutable_catalog_name_path(int index);
  void set_catalog_name_path(int index, const std::string& value);
  void set_catalog_name_path(int index, std::string&& value);
  void set_catalog_name_path(int index, const char* value);
  void set_catalog_name_path(int index, const char* value, size_t size);
  std::string* add_catalog_name_path();
  void add_catalog_name_path(const std::string& value);
  void add_catalog_name_path(std::string&& value);
  void add_catalog_name_path(const char* value);
  void add_catalog_name_path(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& catalog_name_path() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_catalog_name_path();
  private:
  const std::string& _internal_catalog_name_path(int index) const;
  std::string* _internal_add_catalog_name_path();
  public:

  // optional string enum_name = 1;
  bool has_enum_name() const;
  private:
  bool _internal_has_enum_name() const;
  public:
  void clear_enum_name();
  const std::string& enum_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_enum_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_enum_name();
  PROTOBUF_MUST_USE_RESULT std::string* release_enum_name();
  void set_allocated_enum_name(std::string* enum_name);
  private:
  const std::string& _internal_enum_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_enum_name(const std::string& value);
  std::string* _internal_mutable_enum_name();
  public:

  // optional string enum_file_name = 2;
  bool has_enum_file_name() const;
  private:
  bool _internal_has_enum_file_name() const;
  public:
  void clear_enum_file_name();
  const std::string& enum_file_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_enum_file_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_enum_file_name();
  PROTOBUF_MUST_USE_RESULT std::string* release_enum_file_name();
  void set_allocated_enum_file_name(std::string* enum_file_name);
  private:
  const std::string& _internal_enum_file_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_enum_file_name(const std::string& value);
  std::string* _internal_mutable_enum_file_name();
  public:

  // optional int32 file_descriptor_set_index = 3 [default = 0];
  bool has_file_descriptor_set_index() const;
  private:
  bool _internal_has_file_descriptor_set_index() const;
  public:
  void clear_file_descriptor_set_index();
  ::PROTOBUF_NAMESPACE_ID::int32 file_descriptor_set_index() const;
  void set_file_descriptor_set_index(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_file_descriptor_set_index() const;
  void _internal_set_file_descriptor_set_index(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:zetasql.EnumTypeProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> catalog_name_path_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr enum_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr enum_file_name_;
  ::PROTOBUF_NAMESPACE_ID::int32 file_descriptor_set_index_;
  friend struct ::TableStruct_type_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TypeProto

// optional .zetasql.TypeKind type_kind = 1;
inline bool TypeProto::_internal_has_type_kind() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool TypeProto::has_type_kind() const {
  return _internal_has_type_kind();
}
inline void TypeProto::clear_type_kind() {
  type_kind_ = -1;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::zetasql::TypeKind TypeProto::_internal_type_kind() const {
  return static_cast< ::zetasql::TypeKind >(type_kind_);
}
inline ::zetasql::TypeKind TypeProto::type_kind() const {
  // @@protoc_insertion_point(field_get:zetasql.TypeProto.type_kind)
  return _internal_type_kind();
}
inline void TypeProto::_internal_set_type_kind(::zetasql::TypeKind value) {
  assert(::zetasql::TypeKind_IsValid(value));
  _has_bits_[0] |= 0x00000010u;
  type_kind_ = value;
}
inline void TypeProto::set_type_kind(::zetasql::TypeKind value) {
  _internal_set_type_kind(value);
  // @@protoc_insertion_point(field_set:zetasql.TypeProto.type_kind)
}

// optional .zetasql.ArrayTypeProto array_type = 2;
inline bool TypeProto::_internal_has_array_type() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || array_type_ != nullptr);
  return value;
}
inline bool TypeProto::has_array_type() const {
  return _internal_has_array_type();
}
inline void TypeProto::clear_array_type() {
  if (array_type_ != nullptr) array_type_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::zetasql::ArrayTypeProto& TypeProto::_internal_array_type() const {
  const ::zetasql::ArrayTypeProto* p = array_type_;
  return p != nullptr ? *p : reinterpret_cast<const ::zetasql::ArrayTypeProto&>(
      ::zetasql::_ArrayTypeProto_default_instance_);
}
inline const ::zetasql::ArrayTypeProto& TypeProto::array_type() const {
  // @@protoc_insertion_point(field_get:zetasql.TypeProto.array_type)
  return _internal_array_type();
}
inline void TypeProto::unsafe_arena_set_allocated_array_type(
    ::zetasql::ArrayTypeProto* array_type) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(array_type_);
  }
  array_type_ = array_type;
  if (array_type) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:zetasql.TypeProto.array_type)
}
inline ::zetasql::ArrayTypeProto* TypeProto::release_array_type() {
  _has_bits_[0] &= ~0x00000001u;
  ::zetasql::ArrayTypeProto* temp = array_type_;
  array_type_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::zetasql::ArrayTypeProto* TypeProto::unsafe_arena_release_array_type() {
  // @@protoc_insertion_point(field_release:zetasql.TypeProto.array_type)
  _has_bits_[0] &= ~0x00000001u;
  ::zetasql::ArrayTypeProto* temp = array_type_;
  array_type_ = nullptr;
  return temp;
}
inline ::zetasql::ArrayTypeProto* TypeProto::_internal_mutable_array_type() {
  _has_bits_[0] |= 0x00000001u;
  if (array_type_ == nullptr) {
    auto* p = CreateMaybeMessage<::zetasql::ArrayTypeProto>(GetArenaForAllocation());
    array_type_ = p;
  }
  return array_type_;
}
inline ::zetasql::ArrayTypeProto* TypeProto::mutable_array_type() {
  ::zetasql::ArrayTypeProto* _msg = _internal_mutable_array_type();
  // @@protoc_insertion_point(field_mutable:zetasql.TypeProto.array_type)
  return _msg;
}
inline void TypeProto::set_allocated_array_type(::zetasql::ArrayTypeProto* array_type) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete array_type_;
  }
  if (array_type) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::zetasql::ArrayTypeProto>::GetOwningArena(array_type);
    if (message_arena != submessage_arena) {
      array_type = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, array_type, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  array_type_ = array_type;
  // @@protoc_insertion_point(field_set_allocated:zetasql.TypeProto.array_type)
}

// optional .zetasql.StructTypeProto struct_type = 3;
inline bool TypeProto::_internal_has_struct_type() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || struct_type_ != nullptr);
  return value;
}
inline bool TypeProto::has_struct_type() const {
  return _internal_has_struct_type();
}
inline void TypeProto::clear_struct_type() {
  if (struct_type_ != nullptr) struct_type_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::zetasql::StructTypeProto& TypeProto::_internal_struct_type() const {
  const ::zetasql::StructTypeProto* p = struct_type_;
  return p != nullptr ? *p : reinterpret_cast<const ::zetasql::StructTypeProto&>(
      ::zetasql::_StructTypeProto_default_instance_);
}
inline const ::zetasql::StructTypeProto& TypeProto::struct_type() const {
  // @@protoc_insertion_point(field_get:zetasql.TypeProto.struct_type)
  return _internal_struct_type();
}
inline void TypeProto::unsafe_arena_set_allocated_struct_type(
    ::zetasql::StructTypeProto* struct_type) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(struct_type_);
  }
  struct_type_ = struct_type;
  if (struct_type) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:zetasql.TypeProto.struct_type)
}
inline ::zetasql::StructTypeProto* TypeProto::release_struct_type() {
  _has_bits_[0] &= ~0x00000002u;
  ::zetasql::StructTypeProto* temp = struct_type_;
  struct_type_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::zetasql::StructTypeProto* TypeProto::unsafe_arena_release_struct_type() {
  // @@protoc_insertion_point(field_release:zetasql.TypeProto.struct_type)
  _has_bits_[0] &= ~0x00000002u;
  ::zetasql::StructTypeProto* temp = struct_type_;
  struct_type_ = nullptr;
  return temp;
}
inline ::zetasql::StructTypeProto* TypeProto::_internal_mutable_struct_type() {
  _has_bits_[0] |= 0x00000002u;
  if (struct_type_ == nullptr) {
    auto* p = CreateMaybeMessage<::zetasql::StructTypeProto>(GetArenaForAllocation());
    struct_type_ = p;
  }
  return struct_type_;
}
inline ::zetasql::StructTypeProto* TypeProto::mutable_struct_type() {
  ::zetasql::StructTypeProto* _msg = _internal_mutable_struct_type();
  // @@protoc_insertion_point(field_mutable:zetasql.TypeProto.struct_type)
  return _msg;
}
inline void TypeProto::set_allocated_struct_type(::zetasql::StructTypeProto* struct_type) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete struct_type_;
  }
  if (struct_type) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::zetasql::StructTypeProto>::GetOwningArena(struct_type);
    if (message_arena != submessage_arena) {
      struct_type = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, struct_type, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  struct_type_ = struct_type;
  // @@protoc_insertion_point(field_set_allocated:zetasql.TypeProto.struct_type)
}

// optional .zetasql.ProtoTypeProto proto_type = 4;
inline bool TypeProto::_internal_has_proto_type() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || proto_type_ != nullptr);
  return value;
}
inline bool TypeProto::has_proto_type() const {
  return _internal_has_proto_type();
}
inline void TypeProto::clear_proto_type() {
  if (proto_type_ != nullptr) proto_type_->Clear();
  _has_bits_[0] &= ~0x00000004u;
}
inline const ::zetasql::ProtoTypeProto& TypeProto::_internal_proto_type() const {
  const ::zetasql::ProtoTypeProto* p = proto_type_;
  return p != nullptr ? *p : reinterpret_cast<const ::zetasql::ProtoTypeProto&>(
      ::zetasql::_ProtoTypeProto_default_instance_);
}
inline const ::zetasql::ProtoTypeProto& TypeProto::proto_type() const {
  // @@protoc_insertion_point(field_get:zetasql.TypeProto.proto_type)
  return _internal_proto_type();
}
inline void TypeProto::unsafe_arena_set_allocated_proto_type(
    ::zetasql::ProtoTypeProto* proto_type) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(proto_type_);
  }
  proto_type_ = proto_type;
  if (proto_type) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:zetasql.TypeProto.proto_type)
}
inline ::zetasql::ProtoTypeProto* TypeProto::release_proto_type() {
  _has_bits_[0] &= ~0x00000004u;
  ::zetasql::ProtoTypeProto* temp = proto_type_;
  proto_type_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::zetasql::ProtoTypeProto* TypeProto::unsafe_arena_release_proto_type() {
  // @@protoc_insertion_point(field_release:zetasql.TypeProto.proto_type)
  _has_bits_[0] &= ~0x00000004u;
  ::zetasql::ProtoTypeProto* temp = proto_type_;
  proto_type_ = nullptr;
  return temp;
}
inline ::zetasql::ProtoTypeProto* TypeProto::_internal_mutable_proto_type() {
  _has_bits_[0] |= 0x00000004u;
  if (proto_type_ == nullptr) {
    auto* p = CreateMaybeMessage<::zetasql::ProtoTypeProto>(GetArenaForAllocation());
    proto_type_ = p;
  }
  return proto_type_;
}
inline ::zetasql::ProtoTypeProto* TypeProto::mutable_proto_type() {
  ::zetasql::ProtoTypeProto* _msg = _internal_mutable_proto_type();
  // @@protoc_insertion_point(field_mutable:zetasql.TypeProto.proto_type)
  return _msg;
}
inline void TypeProto::set_allocated_proto_type(::zetasql::ProtoTypeProto* proto_type) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete proto_type_;
  }
  if (proto_type) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::zetasql::ProtoTypeProto>::GetOwningArena(proto_type);
    if (message_arena != submessage_arena) {
      proto_type = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, proto_type, submessage_arena);
    }
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  proto_type_ = proto_type;
  // @@protoc_insertion_point(field_set_allocated:zetasql.TypeProto.proto_type)
}

// optional .zetasql.EnumTypeProto enum_type = 5;
inline bool TypeProto::_internal_has_enum_type() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || enum_type_ != nullptr);
  return value;
}
inline bool TypeProto::has_enum_type() const {
  return _internal_has_enum_type();
}
inline void TypeProto::clear_enum_type() {
  if (enum_type_ != nullptr) enum_type_->Clear();
  _has_bits_[0] &= ~0x00000008u;
}
inline const ::zetasql::EnumTypeProto& TypeProto::_internal_enum_type() const {
  const ::zetasql::EnumTypeProto* p = enum_type_;
  return p != nullptr ? *p : reinterpret_cast<const ::zetasql::EnumTypeProto&>(
      ::zetasql::_EnumTypeProto_default_instance_);
}
inline const ::zetasql::EnumTypeProto& TypeProto::enum_type() const {
  // @@protoc_insertion_point(field_get:zetasql.TypeProto.enum_type)
  return _internal_enum_type();
}
inline void TypeProto::unsafe_arena_set_allocated_enum_type(
    ::zetasql::EnumTypeProto* enum_type) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(enum_type_);
  }
  enum_type_ = enum_type;
  if (enum_type) {
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:zetasql.TypeProto.enum_type)
}
inline ::zetasql::EnumTypeProto* TypeProto::release_enum_type() {
  _has_bits_[0] &= ~0x00000008u;
  ::zetasql::EnumTypeProto* temp = enum_type_;
  enum_type_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::zetasql::EnumTypeProto* TypeProto::unsafe_arena_release_enum_type() {
  // @@protoc_insertion_point(field_release:zetasql.TypeProto.enum_type)
  _has_bits_[0] &= ~0x00000008u;
  ::zetasql::EnumTypeProto* temp = enum_type_;
  enum_type_ = nullptr;
  return temp;
}
inline ::zetasql::EnumTypeProto* TypeProto::_internal_mutable_enum_type() {
  _has_bits_[0] |= 0x00000008u;
  if (enum_type_ == nullptr) {
    auto* p = CreateMaybeMessage<::zetasql::EnumTypeProto>(GetArenaForAllocation());
    enum_type_ = p;
  }
  return enum_type_;
}
inline ::zetasql::EnumTypeProto* TypeProto::mutable_enum_type() {
  ::zetasql::EnumTypeProto* _msg = _internal_mutable_enum_type();
  // @@protoc_insertion_point(field_mutable:zetasql.TypeProto.enum_type)
  return _msg;
}
inline void TypeProto::set_allocated_enum_type(::zetasql::EnumTypeProto* enum_type) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete enum_type_;
  }
  if (enum_type) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::zetasql::EnumTypeProto>::GetOwningArena(enum_type);
    if (message_arena != submessage_arena) {
      enum_type = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, enum_type, submessage_arena);
    }
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  enum_type_ = enum_type;
  // @@protoc_insertion_point(field_set_allocated:zetasql.TypeProto.enum_type)
}

// repeated .google.protobuf.FileDescriptorSet file_descriptor_set = 6;
inline int TypeProto::_internal_file_descriptor_set_size() const {
  return file_descriptor_set_.size();
}
inline int TypeProto::file_descriptor_set_size() const {
  return _internal_file_descriptor_set_size();
}
inline PROTOBUF_NAMESPACE_ID::FileDescriptorSet* TypeProto::mutable_file_descriptor_set(int index) {
  // @@protoc_insertion_point(field_mutable:zetasql.TypeProto.file_descriptor_set)
  return file_descriptor_set_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< PROTOBUF_NAMESPACE_ID::FileDescriptorSet >*
TypeProto::mutable_file_descriptor_set() {
  // @@protoc_insertion_point(field_mutable_list:zetasql.TypeProto.file_descriptor_set)
  return &file_descriptor_set_;
}
inline const PROTOBUF_NAMESPACE_ID::FileDescriptorSet& TypeProto::_internal_file_descriptor_set(int index) const {
  return file_descriptor_set_.Get(index);
}
inline const PROTOBUF_NAMESPACE_ID::FileDescriptorSet& TypeProto::file_descriptor_set(int index) const {
  // @@protoc_insertion_point(field_get:zetasql.TypeProto.file_descriptor_set)
  return _internal_file_descriptor_set(index);
}
inline PROTOBUF_NAMESPACE_ID::FileDescriptorSet* TypeProto::_internal_add_file_descriptor_set() {
  return file_descriptor_set_.Add();
}
inline PROTOBUF_NAMESPACE_ID::FileDescriptorSet* TypeProto::add_file_descriptor_set() {
  PROTOBUF_NAMESPACE_ID::FileDescriptorSet* _add = _internal_add_file_descriptor_set();
  // @@protoc_insertion_point(field_add:zetasql.TypeProto.file_descriptor_set)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< PROTOBUF_NAMESPACE_ID::FileDescriptorSet >&
TypeProto::file_descriptor_set() const {
  // @@protoc_insertion_point(field_list:zetasql.TypeProto.file_descriptor_set)
  return file_descriptor_set_;
}

// -------------------------------------------------------------------

// ArrayTypeProto

// optional .zetasql.TypeProto element_type = 1;
inline bool ArrayTypeProto::_internal_has_element_type() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || element_type_ != nullptr);
  return value;
}
inline bool ArrayTypeProto::has_element_type() const {
  return _internal_has_element_type();
}
inline void ArrayTypeProto::clear_element_type() {
  if (element_type_ != nullptr) element_type_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::zetasql::TypeProto& ArrayTypeProto::_internal_element_type() const {
  const ::zetasql::TypeProto* p = element_type_;
  return p != nullptr ? *p : reinterpret_cast<const ::zetasql::TypeProto&>(
      ::zetasql::_TypeProto_default_instance_);
}
inline const ::zetasql::TypeProto& ArrayTypeProto::element_type() const {
  // @@protoc_insertion_point(field_get:zetasql.ArrayTypeProto.element_type)
  return _internal_element_type();
}
inline void ArrayTypeProto::unsafe_arena_set_allocated_element_type(
    ::zetasql::TypeProto* element_type) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(element_type_);
  }
  element_type_ = element_type;
  if (element_type) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:zetasql.ArrayTypeProto.element_type)
}
inline ::zetasql::TypeProto* ArrayTypeProto::release_element_type() {
  _has_bits_[0] &= ~0x00000001u;
  ::zetasql::TypeProto* temp = element_type_;
  element_type_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::zetasql::TypeProto* ArrayTypeProto::unsafe_arena_release_element_type() {
  // @@protoc_insertion_point(field_release:zetasql.ArrayTypeProto.element_type)
  _has_bits_[0] &= ~0x00000001u;
  ::zetasql::TypeProto* temp = element_type_;
  element_type_ = nullptr;
  return temp;
}
inline ::zetasql::TypeProto* ArrayTypeProto::_internal_mutable_element_type() {
  _has_bits_[0] |= 0x00000001u;
  if (element_type_ == nullptr) {
    auto* p = CreateMaybeMessage<::zetasql::TypeProto>(GetArenaForAllocation());
    element_type_ = p;
  }
  return element_type_;
}
inline ::zetasql::TypeProto* ArrayTypeProto::mutable_element_type() {
  ::zetasql::TypeProto* _msg = _internal_mutable_element_type();
  // @@protoc_insertion_point(field_mutable:zetasql.ArrayTypeProto.element_type)
  return _msg;
}
inline void ArrayTypeProto::set_allocated_element_type(::zetasql::TypeProto* element_type) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete element_type_;
  }
  if (element_type) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::zetasql::TypeProto>::GetOwningArena(element_type);
    if (message_arena != submessage_arena) {
      element_type = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, element_type, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  element_type_ = element_type;
  // @@protoc_insertion_point(field_set_allocated:zetasql.ArrayTypeProto.element_type)
}

// -------------------------------------------------------------------

// StructFieldProto

// optional string field_name = 1;
inline bool StructFieldProto::_internal_has_field_name() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool StructFieldProto::has_field_name() const {
  return _internal_has_field_name();
}
inline void StructFieldProto::clear_field_name() {
  field_name_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& StructFieldProto::field_name() const {
  // @@protoc_insertion_point(field_get:zetasql.StructFieldProto.field_name)
  return _internal_field_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void StructFieldProto::set_field_name(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 field_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:zetasql.StructFieldProto.field_name)
}
inline std::string* StructFieldProto::mutable_field_name() {
  std::string* _s = _internal_mutable_field_name();
  // @@protoc_insertion_point(field_mutable:zetasql.StructFieldProto.field_name)
  return _s;
}
inline const std::string& StructFieldProto::_internal_field_name() const {
  return field_name_.Get();
}
inline void StructFieldProto::_internal_set_field_name(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  field_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* StructFieldProto::_internal_mutable_field_name() {
  _has_bits_[0] |= 0x00000001u;
  return field_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* StructFieldProto::release_field_name() {
  // @@protoc_insertion_point(field_release:zetasql.StructFieldProto.field_name)
  if (!_internal_has_field_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return field_name_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void StructFieldProto::set_allocated_field_name(std::string* field_name) {
  if (field_name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  field_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), field_name,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:zetasql.StructFieldProto.field_name)
}

// optional .zetasql.TypeProto field_type = 2;
inline bool StructFieldProto::_internal_has_field_type() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || field_type_ != nullptr);
  return value;
}
inline bool StructFieldProto::has_field_type() const {
  return _internal_has_field_type();
}
inline void StructFieldProto::clear_field_type() {
  if (field_type_ != nullptr) field_type_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::zetasql::TypeProto& StructFieldProto::_internal_field_type() const {
  const ::zetasql::TypeProto* p = field_type_;
  return p != nullptr ? *p : reinterpret_cast<const ::zetasql::TypeProto&>(
      ::zetasql::_TypeProto_default_instance_);
}
inline const ::zetasql::TypeProto& StructFieldProto::field_type() const {
  // @@protoc_insertion_point(field_get:zetasql.StructFieldProto.field_type)
  return _internal_field_type();
}
inline void StructFieldProto::unsafe_arena_set_allocated_field_type(
    ::zetasql::TypeProto* field_type) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(field_type_);
  }
  field_type_ = field_type;
  if (field_type) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:zetasql.StructFieldProto.field_type)
}
inline ::zetasql::TypeProto* StructFieldProto::release_field_type() {
  _has_bits_[0] &= ~0x00000002u;
  ::zetasql::TypeProto* temp = field_type_;
  field_type_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::zetasql::TypeProto* StructFieldProto::unsafe_arena_release_field_type() {
  // @@protoc_insertion_point(field_release:zetasql.StructFieldProto.field_type)
  _has_bits_[0] &= ~0x00000002u;
  ::zetasql::TypeProto* temp = field_type_;
  field_type_ = nullptr;
  return temp;
}
inline ::zetasql::TypeProto* StructFieldProto::_internal_mutable_field_type() {
  _has_bits_[0] |= 0x00000002u;
  if (field_type_ == nullptr) {
    auto* p = CreateMaybeMessage<::zetasql::TypeProto>(GetArenaForAllocation());
    field_type_ = p;
  }
  return field_type_;
}
inline ::zetasql::TypeProto* StructFieldProto::mutable_field_type() {
  ::zetasql::TypeProto* _msg = _internal_mutable_field_type();
  // @@protoc_insertion_point(field_mutable:zetasql.StructFieldProto.field_type)
  return _msg;
}
inline void StructFieldProto::set_allocated_field_type(::zetasql::TypeProto* field_type) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete field_type_;
  }
  if (field_type) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::zetasql::TypeProto>::GetOwningArena(field_type);
    if (message_arena != submessage_arena) {
      field_type = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, field_type, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  field_type_ = field_type;
  // @@protoc_insertion_point(field_set_allocated:zetasql.StructFieldProto.field_type)
}

// -------------------------------------------------------------------

// StructTypeProto

// repeated .zetasql.StructFieldProto field = 1;
inline int StructTypeProto::_internal_field_size() const {
  return field_.size();
}
inline int StructTypeProto::field_size() const {
  return _internal_field_size();
}
inline void StructTypeProto::clear_field() {
  field_.Clear();
}
inline ::zetasql::StructFieldProto* StructTypeProto::mutable_field(int index) {
  // @@protoc_insertion_point(field_mutable:zetasql.StructTypeProto.field)
  return field_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::zetasql::StructFieldProto >*
StructTypeProto::mutable_field() {
  // @@protoc_insertion_point(field_mutable_list:zetasql.StructTypeProto.field)
  return &field_;
}
inline const ::zetasql::StructFieldProto& StructTypeProto::_internal_field(int index) const {
  return field_.Get(index);
}
inline const ::zetasql::StructFieldProto& StructTypeProto::field(int index) const {
  // @@protoc_insertion_point(field_get:zetasql.StructTypeProto.field)
  return _internal_field(index);
}
inline ::zetasql::StructFieldProto* StructTypeProto::_internal_add_field() {
  return field_.Add();
}
inline ::zetasql::StructFieldProto* StructTypeProto::add_field() {
  ::zetasql::StructFieldProto* _add = _internal_add_field();
  // @@protoc_insertion_point(field_add:zetasql.StructTypeProto.field)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::zetasql::StructFieldProto >&
StructTypeProto::field() const {
  // @@protoc_insertion_point(field_list:zetasql.StructTypeProto.field)
  return field_;
}

// -------------------------------------------------------------------

// ProtoTypeProto

// optional string proto_name = 1;
inline bool ProtoTypeProto::_internal_has_proto_name() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool ProtoTypeProto::has_proto_name() const {
  return _internal_has_proto_name();
}
inline void ProtoTypeProto::clear_proto_name() {
  proto_name_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ProtoTypeProto::proto_name() const {
  // @@protoc_insertion_point(field_get:zetasql.ProtoTypeProto.proto_name)
  return _internal_proto_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ProtoTypeProto::set_proto_name(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 proto_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:zetasql.ProtoTypeProto.proto_name)
}
inline std::string* ProtoTypeProto::mutable_proto_name() {
  std::string* _s = _internal_mutable_proto_name();
  // @@protoc_insertion_point(field_mutable:zetasql.ProtoTypeProto.proto_name)
  return _s;
}
inline const std::string& ProtoTypeProto::_internal_proto_name() const {
  return proto_name_.Get();
}
inline void ProtoTypeProto::_internal_set_proto_name(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  proto_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ProtoTypeProto::_internal_mutable_proto_name() {
  _has_bits_[0] |= 0x00000001u;
  return proto_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ProtoTypeProto::release_proto_name() {
  // @@protoc_insertion_point(field_release:zetasql.ProtoTypeProto.proto_name)
  if (!_internal_has_proto_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return proto_name_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ProtoTypeProto::set_allocated_proto_name(std::string* proto_name) {
  if (proto_name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  proto_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), proto_name,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:zetasql.ProtoTypeProto.proto_name)
}

// optional string proto_file_name = 2;
inline bool ProtoTypeProto::_internal_has_proto_file_name() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool ProtoTypeProto::has_proto_file_name() const {
  return _internal_has_proto_file_name();
}
inline void ProtoTypeProto::clear_proto_file_name() {
  proto_file_name_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& ProtoTypeProto::proto_file_name() const {
  // @@protoc_insertion_point(field_get:zetasql.ProtoTypeProto.proto_file_name)
  return _internal_proto_file_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ProtoTypeProto::set_proto_file_name(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000002u;
 proto_file_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:zetasql.ProtoTypeProto.proto_file_name)
}
inline std::string* ProtoTypeProto::mutable_proto_file_name() {
  std::string* _s = _internal_mutable_proto_file_name();
  // @@protoc_insertion_point(field_mutable:zetasql.ProtoTypeProto.proto_file_name)
  return _s;
}
inline const std::string& ProtoTypeProto::_internal_proto_file_name() const {
  return proto_file_name_.Get();
}
inline void ProtoTypeProto::_internal_set_proto_file_name(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  proto_file_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ProtoTypeProto::_internal_mutable_proto_file_name() {
  _has_bits_[0] |= 0x00000002u;
  return proto_file_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ProtoTypeProto::release_proto_file_name() {
  // @@protoc_insertion_point(field_release:zetasql.ProtoTypeProto.proto_file_name)
  if (!_internal_has_proto_file_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return proto_file_name_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ProtoTypeProto::set_allocated_proto_file_name(std::string* proto_file_name) {
  if (proto_file_name != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  proto_file_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), proto_file_name,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:zetasql.ProtoTypeProto.proto_file_name)
}

// optional int32 file_descriptor_set_index = 3 [default = 0];
inline bool ProtoTypeProto::_internal_has_file_descriptor_set_index() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool ProtoTypeProto::has_file_descriptor_set_index() const {
  return _internal_has_file_descriptor_set_index();
}
inline void ProtoTypeProto::clear_file_descriptor_set_index() {
  file_descriptor_set_index_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ProtoTypeProto::_internal_file_descriptor_set_index() const {
  return file_descriptor_set_index_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ProtoTypeProto::file_descriptor_set_index() const {
  // @@protoc_insertion_point(field_get:zetasql.ProtoTypeProto.file_descriptor_set_index)
  return _internal_file_descriptor_set_index();
}
inline void ProtoTypeProto::_internal_set_file_descriptor_set_index(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000004u;
  file_descriptor_set_index_ = value;
}
inline void ProtoTypeProto::set_file_descriptor_set_index(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_file_descriptor_set_index(value);
  // @@protoc_insertion_point(field_set:zetasql.ProtoTypeProto.file_descriptor_set_index)
}

// repeated string catalog_name_path = 4;
inline int ProtoTypeProto::_internal_catalog_name_path_size() const {
  return catalog_name_path_.size();
}
inline int ProtoTypeProto::catalog_name_path_size() const {
  return _internal_catalog_name_path_size();
}
inline void ProtoTypeProto::clear_catalog_name_path() {
  catalog_name_path_.Clear();
}
inline std::string* ProtoTypeProto::add_catalog_name_path() {
  std::string* _s = _internal_add_catalog_name_path();
  // @@protoc_insertion_point(field_add_mutable:zetasql.ProtoTypeProto.catalog_name_path)
  return _s;
}
inline const std::string& ProtoTypeProto::_internal_catalog_name_path(int index) const {
  return catalog_name_path_.Get(index);
}
inline const std::string& ProtoTypeProto::catalog_name_path(int index) const {
  // @@protoc_insertion_point(field_get:zetasql.ProtoTypeProto.catalog_name_path)
  return _internal_catalog_name_path(index);
}
inline std::string* ProtoTypeProto::mutable_catalog_name_path(int index) {
  // @@protoc_insertion_point(field_mutable:zetasql.ProtoTypeProto.catalog_name_path)
  return catalog_name_path_.Mutable(index);
}
inline void ProtoTypeProto::set_catalog_name_path(int index, const std::string& value) {
  catalog_name_path_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:zetasql.ProtoTypeProto.catalog_name_path)
}
inline void ProtoTypeProto::set_catalog_name_path(int index, std::string&& value) {
  catalog_name_path_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:zetasql.ProtoTypeProto.catalog_name_path)
}
inline void ProtoTypeProto::set_catalog_name_path(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  catalog_name_path_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:zetasql.ProtoTypeProto.catalog_name_path)
}
inline void ProtoTypeProto::set_catalog_name_path(int index, const char* value, size_t size) {
  catalog_name_path_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:zetasql.ProtoTypeProto.catalog_name_path)
}
inline std::string* ProtoTypeProto::_internal_add_catalog_name_path() {
  return catalog_name_path_.Add();
}
inline void ProtoTypeProto::add_catalog_name_path(const std::string& value) {
  catalog_name_path_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:zetasql.ProtoTypeProto.catalog_name_path)
}
inline void ProtoTypeProto::add_catalog_name_path(std::string&& value) {
  catalog_name_path_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:zetasql.ProtoTypeProto.catalog_name_path)
}
inline void ProtoTypeProto::add_catalog_name_path(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  catalog_name_path_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:zetasql.ProtoTypeProto.catalog_name_path)
}
inline void ProtoTypeProto::add_catalog_name_path(const char* value, size_t size) {
  catalog_name_path_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:zetasql.ProtoTypeProto.catalog_name_path)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
ProtoTypeProto::catalog_name_path() const {
  // @@protoc_insertion_point(field_list:zetasql.ProtoTypeProto.catalog_name_path)
  return catalog_name_path_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
ProtoTypeProto::mutable_catalog_name_path() {
  // @@protoc_insertion_point(field_mutable_list:zetasql.ProtoTypeProto.catalog_name_path)
  return &catalog_name_path_;
}

// -------------------------------------------------------------------

// EnumTypeProto

// optional string enum_name = 1;
inline bool EnumTypeProto::_internal_has_enum_name() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool EnumTypeProto::has_enum_name() const {
  return _internal_has_enum_name();
}
inline void EnumTypeProto::clear_enum_name() {
  enum_name_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& EnumTypeProto::enum_name() const {
  // @@protoc_insertion_point(field_get:zetasql.EnumTypeProto.enum_name)
  return _internal_enum_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void EnumTypeProto::set_enum_name(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 enum_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:zetasql.EnumTypeProto.enum_name)
}
inline std::string* EnumTypeProto::mutable_enum_name() {
  std::string* _s = _internal_mutable_enum_name();
  // @@protoc_insertion_point(field_mutable:zetasql.EnumTypeProto.enum_name)
  return _s;
}
inline const std::string& EnumTypeProto::_internal_enum_name() const {
  return enum_name_.Get();
}
inline void EnumTypeProto::_internal_set_enum_name(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  enum_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* EnumTypeProto::_internal_mutable_enum_name() {
  _has_bits_[0] |= 0x00000001u;
  return enum_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* EnumTypeProto::release_enum_name() {
  // @@protoc_insertion_point(field_release:zetasql.EnumTypeProto.enum_name)
  if (!_internal_has_enum_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return enum_name_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void EnumTypeProto::set_allocated_enum_name(std::string* enum_name) {
  if (enum_name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  enum_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), enum_name,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:zetasql.EnumTypeProto.enum_name)
}

// optional string enum_file_name = 2;
inline bool EnumTypeProto::_internal_has_enum_file_name() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool EnumTypeProto::has_enum_file_name() const {
  return _internal_has_enum_file_name();
}
inline void EnumTypeProto::clear_enum_file_name() {
  enum_file_name_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& EnumTypeProto::enum_file_name() const {
  // @@protoc_insertion_point(field_get:zetasql.EnumTypeProto.enum_file_name)
  return _internal_enum_file_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void EnumTypeProto::set_enum_file_name(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000002u;
 enum_file_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:zetasql.EnumTypeProto.enum_file_name)
}
inline std::string* EnumTypeProto::mutable_enum_file_name() {
  std::string* _s = _internal_mutable_enum_file_name();
  // @@protoc_insertion_point(field_mutable:zetasql.EnumTypeProto.enum_file_name)
  return _s;
}
inline const std::string& EnumTypeProto::_internal_enum_file_name() const {
  return enum_file_name_.Get();
}
inline void EnumTypeProto::_internal_set_enum_file_name(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  enum_file_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* EnumTypeProto::_internal_mutable_enum_file_name() {
  _has_bits_[0] |= 0x00000002u;
  return enum_file_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* EnumTypeProto::release_enum_file_name() {
  // @@protoc_insertion_point(field_release:zetasql.EnumTypeProto.enum_file_name)
  if (!_internal_has_enum_file_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return enum_file_name_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void EnumTypeProto::set_allocated_enum_file_name(std::string* enum_file_name) {
  if (enum_file_name != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  enum_file_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), enum_file_name,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:zetasql.EnumTypeProto.enum_file_name)
}

// optional int32 file_descriptor_set_index = 3 [default = 0];
inline bool EnumTypeProto::_internal_has_file_descriptor_set_index() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool EnumTypeProto::has_file_descriptor_set_index() const {
  return _internal_has_file_descriptor_set_index();
}
inline void EnumTypeProto::clear_file_descriptor_set_index() {
  file_descriptor_set_index_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 EnumTypeProto::_internal_file_descriptor_set_index() const {
  return file_descriptor_set_index_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 EnumTypeProto::file_descriptor_set_index() const {
  // @@protoc_insertion_point(field_get:zetasql.EnumTypeProto.file_descriptor_set_index)
  return _internal_file_descriptor_set_index();
}
inline void EnumTypeProto::_internal_set_file_descriptor_set_index(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000004u;
  file_descriptor_set_index_ = value;
}
inline void EnumTypeProto::set_file_descriptor_set_index(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_file_descriptor_set_index(value);
  // @@protoc_insertion_point(field_set:zetasql.EnumTypeProto.file_descriptor_set_index)
}

// repeated string catalog_name_path = 4;
inline int EnumTypeProto::_internal_catalog_name_path_size() const {
  return catalog_name_path_.size();
}
inline int EnumTypeProto::catalog_name_path_size() const {
  return _internal_catalog_name_path_size();
}
inline void EnumTypeProto::clear_catalog_name_path() {
  catalog_name_path_.Clear();
}
inline std::string* EnumTypeProto::add_catalog_name_path() {
  std::string* _s = _internal_add_catalog_name_path();
  // @@protoc_insertion_point(field_add_mutable:zetasql.EnumTypeProto.catalog_name_path)
  return _s;
}
inline const std::string& EnumTypeProto::_internal_catalog_name_path(int index) const {
  return catalog_name_path_.Get(index);
}
inline const std::string& EnumTypeProto::catalog_name_path(int index) const {
  // @@protoc_insertion_point(field_get:zetasql.EnumTypeProto.catalog_name_path)
  return _internal_catalog_name_path(index);
}
inline std::string* EnumTypeProto::mutable_catalog_name_path(int index) {
  // @@protoc_insertion_point(field_mutable:zetasql.EnumTypeProto.catalog_name_path)
  return catalog_name_path_.Mutable(index);
}
inline void EnumTypeProto::set_catalog_name_path(int index, const std::string& value) {
  catalog_name_path_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:zetasql.EnumTypeProto.catalog_name_path)
}
inline void EnumTypeProto::set_catalog_name_path(int index, std::string&& value) {
  catalog_name_path_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:zetasql.EnumTypeProto.catalog_name_path)
}
inline void EnumTypeProto::set_catalog_name_path(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  catalog_name_path_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:zetasql.EnumTypeProto.catalog_name_path)
}
inline void EnumTypeProto::set_catalog_name_path(int index, const char* value, size_t size) {
  catalog_name_path_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:zetasql.EnumTypeProto.catalog_name_path)
}
inline std::string* EnumTypeProto::_internal_add_catalog_name_path() {
  return catalog_name_path_.Add();
}
inline void EnumTypeProto::add_catalog_name_path(const std::string& value) {
  catalog_name_path_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:zetasql.EnumTypeProto.catalog_name_path)
}
inline void EnumTypeProto::add_catalog_name_path(std::string&& value) {
  catalog_name_path_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:zetasql.EnumTypeProto.catalog_name_path)
}
inline void EnumTypeProto::add_catalog_name_path(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  catalog_name_path_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:zetasql.EnumTypeProto.catalog_name_path)
}
inline void EnumTypeProto::add_catalog_name_path(const char* value, size_t size) {
  catalog_name_path_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:zetasql.EnumTypeProto.catalog_name_path)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
EnumTypeProto::catalog_name_path() const {
  // @@protoc_insertion_point(field_list:zetasql.EnumTypeProto.catalog_name_path)
  return catalog_name_path_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
EnumTypeProto::mutable_catalog_name_path() {
  // @@protoc_insertion_point(field_mutable_list:zetasql.EnumTypeProto.catalog_name_path)
  return &catalog_name_path_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace zetasql

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::zetasql::TypeKind> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::zetasql::TypeKind>() {
  return ::zetasql::TypeKind_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_type_2eproto
