name: tag
on:
  release:
    types: [ published ]
jobs:
  osx:
    name: Create artifacts on macOS-latest
    runs-on: macOS-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Cache
        uses: actions/cache@v2
        with:
          path: /private/var/tmp
          key: ${{ runner.os }}-bazel-build-${{ hashFiles('./**') }}
          restore-keys: ${{ runner.os }}-bazel-build-
      - name: Install bazel 1.0.0 and Build
        shell: bash
        run: |
          (cd "/usr/local/Cellar/bazel/3.3.1/libexec/bin" && curl -LO https://releases.bazel.build/1.0.0/release/bazel-1.0.0-darwin-x86_64 && chmod +x bazel-1.0.0-darwin-x86_64)
          make osx
          mv ./bazel-bin/alphasql alphasql_darwin_amd64
          tar -zcvf bin/alphasql_darwin_amd64.tar.gz alphasql_darwin_amd64
      - name: Get Release
        id: get
        uses: bruceadams/get-release@v1
      - name: Upload OSX Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./bin/alphasql_darwin_amd64.tar.gz
          asset_name: alphasql_darwin_amd64.tar.gz
          asset_content_type: application/tar+gzip

  linux:
    name: Create artifacts on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/bazel
          key: ${{ runner.os }}-bazel-build-${{ hashFiles('./**') }}
          restore-keys: ${{ runner.os }}-bazel-build-
      - name: Install bazel 1.0.0 and Build
        run: |
            sudo apt-get update && \
                sudo apt-get install tzdata build-essential software-properties-common -y && \
                sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y && \
                sudo apt-get update && \
                sudo apt-get install --no-install-recommends -y make gcc-9 g++-9 && \
                sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 900 \
                    --slave /usr/bin/g++ g++ /usr/bin/g++-9
            sudo apt install curl gnupg
            curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
            echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
            sudo apt update && sudo apt install bazel-1.0.0
            bazel build //...
            mv ./bazel-bin/alphasql alphasql_linux_x86_64
            tar -zcvf bin/alphasql_linux_x86_64.tar.gz alphasql_linux_x86_64
      - name: Get Release
        id: get
        uses: bruceadams/get-release@v1
      - name: Upload Linux Asset
        id: upload-linux-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./bin/alphasql_linux_x86_64.tar.gz
          asset_name: alphasql_linux_x86_64.tar.gz
          asset_content_type: application/tar+gzip

  docker-hub:
    name: Push image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Docker Build and Push
        uses: docker/build-push-action@v1
        env:
          DOCKER_BUILDKIT: 1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: matts966/alphasql
          tag_with_ref: true
          dockerfile: docker/Dockerfile
          cache_froms: matts966/alphasql:latest

  docker-github:
    name: Push image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        env:
          DOCKER_BUILDKIT: 1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: matts966/alphasql/alphasql
          tag_with_ref: true
          dockerfile: docker/Dockerfile
          cache_froms: matts966/alphasql:latest
