name: test
on: push
jobs:
  linux:
    name: Test the repository on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/bazel
          key: ${{ runner.os }}-bazel-build-${{ hashFiles('./**') }}
          restore-keys: ${{ runner.os }}-bazel-build-
      - name: Test the repository
        run: |
          bazelisk test --test_output=errors //alphasql/...

  osx:
    name: Test the repository on Mac
    runs-on: macOS-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Cache
        uses: actions/cache@v2
        with:
          path: /private/var/tmp
          key: ${{ runner.os }}-bazel-build-${{ hashFiles('./**') }}
          restore-keys: ${{ runner.os }}-bazel-build-
      - name: Test the repository
        shell: bash
        run: |
          bazelisk test --test_output=errors //alphasql/...
