name: test
on: push
jobs:
  linux:
    name: Test the repository on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/bazel
          key: ${{ runner.os }}-bazelisk-build-${{ hashFiles('./**') }}
          restore-keys: ${{ runner.os }}-bazelisk-build-
      - name: Test the repository
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y gcc-9 g++-9
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 900 \
            --slave /usr/bin/g++ g++ /usr/bin/g++-9
          bazelisk test --test_output=errors //alphasql/...

  osx:
    name: Test the repository on Mac
    runs-on: macOS-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Cache
        uses: actions/cache@v2
        with:
          path: /private/var/tmp
          key: ${{ runner.os }}-bazelisk-build-${{ hashFiles('./**') }}
          restore-keys: ${{ runner.os }}-bazelisk-build-
      - name: Test the repository
        shell: bash
        run: |
          make
