name: test
on: push
env:
  cache-version: v1.0.0
jobs:
  linux:
    name: Test the repository on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/bazel
          key: ${{ env.cache-version }}-${{ runner.os }}-bazelisk-build-${{ hashFiles('./**') }}
          restore-keys: ${{ env.cache-version }}-${{ runner.os }}-bazelisk-build-
      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y gcc-9 g++-9
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 900 \
            --slave /usr/bin/g++ g++ /usr/bin/g++-9
          bazelisk build //alphasql/...
          bazelisk test --test_output=errors //alphasql/...

          alphadag ./samples/sample
          alphadag --output_path=dag.dot ./samples/sample
          alphadag --external_required_tables_output_path=dag.dot ./samples/sample


  osx:
    name: Test the repository on Mac
    runs-on: macos-10.15
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Cache
        uses: actions/cache@v2
        with:
          path: /private/var/tmp/*bazel*
          key: ${{ env.cache-version }}-${{ runner.os }}-bazelisk-build-${{ hashFiles('./**') }}
          restore-keys: ${{ env.cache-version }}-${{ runner.os }}-bazelisk-build-
      - name: Test the repository
        run: |
          brew install graphviz
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          bazel shutdown
          make

          alphadag ./samples/sample
          alphadag --output_path=dag.dot ./samples/sample
          alphadag --external_required_tables_output_path=dag.dot ./samples/sample
