name: test
on: push
env:
  cache-version: v1
jobs:
  linux:
    name: Test the repository on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/bazel
          key: ${{ env.cache-version }}-${{ runner.os }}-bazelisk-build-${{ hashFiles('./**') }}
          restore-keys: ${{ env.cache-version }}-${{ runner.os }}-bazelisk-build-
      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y gcc-9 g++-9
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 900 \
            --slave /usr/bin/g++ g++ /usr/bin/g++-9
          bazelisk test --test_output=errors //alphasql/...
      - name: Test installation
        run: |
          temp=$(mktemp -d)
          wget -P $temp https://github.com/Matts966/alphasql/releases/latest/download/alphasql_linux_x86_64.tar.gz \
            && sudo tar -zxvf $temp/alphasql_linux_x86_64.tar.gz -C /usr/local/bin --strip=1
          alphadag ./samples/sample


  osx:
    name: Test the repository on Mac
    runs-on: macOS-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Cache
        uses: actions/cache@v2
        with:
          path: /private/var/tmp/*bazel*
          key: ${{ env.cache-version }}-${{ runner.os }}-bazelisk-build-${{ hashFiles('./**') }}
          restore-keys: ${{ env.cache-version }}-${{ runner.os }}-bazelisk-build-
      - name: Test the repository
        run: |
          make test
      - name: Test installation
        shell: bash
        run: |
          temp=$(mktemp -d)
          wget -P $temp https://github.com/Matts966/alphasql/releases/latest/download/alphasql_darwin_x86_64.tar.gz \
            && sudo tar -zxvf $temp/alphasql_darwin_x86_64.tar.gz -C /usr/local/bin --strip=1
          alphadag ./samples/sample
