name: test
on: push
env:
  cache-version: v1.0.0
jobs:
  linux:
    name: Test the repository on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Cache
        uses: pat-s/always-upload-cache@v2.1.5
        with:
          path: ~/.cache/bazel
          key: ${{ env.cache-version }}-${{ runner.os }}-bazelisk-build-${{ hashFiles('./**') }}
          restore-keys: ${{ env.cache-version }}-${{ runner.os }}-bazelisk-build-
      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y gcc-9 g++-9 graphviz
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 900 \
            --slave /usr/bin/g++ g++ /usr/bin/g++-9
          make
      - name: Test
        run: |
          echo 🚨 checking sample testing result...
          echo 🚨 exit if not up-to-date
          # TODO: check dag output isomorphism
          git diff --exit-code -- '*.txt'

          alphadag ./samples/sample
          alphadag --output_path=dag.dot ./samples/sample
          alphadag --external_required_tables_output_path=dag.dot ./samples/sample

  osx:
    name: Test the repository on Mac
    runs-on: macos-10.15
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Cache
        uses: pat-s/always-upload-cache@v2.1.5
        with:
          path: ~/.cache/bazel
          key: ${{ env.cache-version }}-${{ runner.os }}-bazelisk-build-${{ hashFiles('./**') }}
          restore-keys: ${{ env.cache-version }}-${{ runner.os }}-bazelisk-build-
      - name: Setup
        run: |
          brew install graphviz
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          bazel shutdown
          export CC=g++
          make
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update Snapshot
          reviewers: Matts966
          branch: snapshot-testing
          delete-branch: true
          title: 'Updated Snapshot :tada:'
          body: |
            Updated Snapshot :tada:
            Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
      - name: Test
        run: |
          echo 🚨 checking sample testing result...
          echo 🚨 exit if not up-to-date
          # TODO: check dag output isomorphism
          git diff --exit-code -- '*.txt'

          alphadag ./samples/sample
          alphadag --output_path=dag.dot ./samples/sample
          alphadag --external_required_tables_output_path=dag.dot ./samples/sample
