name: test
on: push
jobs:
  test:
    name: Test the repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Test the repository
        run: |
            sudo apt-get install -y tzdata
            sudo apt install curl gnupg
            curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
            echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
            sudo apt update && sudo apt install bazel-1.0.0
            bazel test //zetasql/...
